version: '3.7'
services:
    postgres:
        image: postgres:11.9
        environment:
          - POSTGRES_USER=reviews_microservice
          - POSTGRES_PASSWORD=reviews_microservice
          - POSTGRES_DB=reviews_microservice
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 54321:5432
        volumes:
          - /var/lib/postgresql/data/pgdata
        logging:
            options:
                max-size: 10m
                max-file: "3"
    api:
      container_name: reviews_microservice_api
      depends_on:
        - postgres
      build:
        context: ../
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgres://reviews_microservice:reviews_microservice@postgres/reviews_microservice
      entrypoint: /app/docker-compose/api-entrypoint.sh
